spring:
  application:
    name: app-microservice-auth
  webflux:
    base-path: /app-microservice-auth
  r2dbc:
    url: r2dbc:postgresql://${DB_AUTH_HOST:localhost}:${DB_AUTH_PORT:5432}/${DB_AUTH_NAME:authdb}
    username: ${DB_AUTH_USER:brayanpv}
    password: ${DB_AUTH_PASSWORD:brayanpv}

server:
  port: 8000
  address: 0.0.0.0

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_KEY:}
  expiration: ${JWT_EXPIRATION:86400000}